version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=3121997000123
      - MYSQL_DATABASE=formdb
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 3121997000123
      MYSQL_DATABASE: formdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql  # Update path to schema.sql

volumes:
  db_data:

