apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
data:
  schema.sql: |
    CREATE DATABASE IF NOT EXISTS formdb;
    USE formdb;
    
    CREATE TABLE IF NOT EXISTS form_data (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(100),
      email VARCHAR(100),
      message TEXT
    );
