apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels: 
        app: mysql
    spec:
      initContainers:
      - name: init-mysql-db
        image: mysql:5.7
        command:
        - "sh"
        - "-c"
        - >
          mysql -u root -p$MYSQL_ROOT_PASSWORD < /docker-entrypoint-initdb.d/schema.sql;
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "3121997000123"
        volumeMounts:
          - name: init-script 
            mountPath: /docker-entrypoint-initdb.d

      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "3121997000123"
        - name: MYSQL_DATABASE
          value: "formdb"
        ports:
        - containerPort: 3306
          name: mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      - name: init-script
        configMap:
          name: mysql-init-script
